INFO 2012-08-16 15:01:20,194 models Dispatch a task name mafengwo, {u'SHUTDOWN': True}
ERROR 2012-08-16 15:01:20,195 mafengwo u'start'
ERROR 2012-08-16 15:01:20,586 mafengwo u'start'
INFO 2012-08-16 15:01:20,586 models Dispatch a task name mafengwo, {u'SHUTDOWN': True}
INFO 2012-08-16 15:09:56,155 models Will handle task mafengwo, num 2
INFO 2012-08-16 15:09:56,156 models Will send task mafengwo, num 2
INFO 2012-08-16 15:09:56,156 clients Send jobs task num 2
INFO 2012-08-16 15:10:37,619 models Will handle task mafengwo, num 2
INFO 2012-08-16 15:10:37,619 models Will send task mafengwo, num 2
INFO 2012-08-16 15:10:37,620 clients Send jobs task num 2
INFO 2012-08-16 15:10:59,627 models Will handle task mafengwo, num 2
INFO 2012-08-16 15:10:59,627 models Will send task mafengwo, num 2
INFO 2012-08-16 15:10:59,627 clients Send jobs task num 2
INFO 2012-08-16 15:16:43,907 models Will handle task mafengwo, num 2
INFO 2012-08-16 15:16:43,908 models Will send task mafengwo, num 2
INFO 2012-08-16 15:16:43,908 clients Send jobs task num 2
INFO 2012-08-16 15:17:02,243 models Will handle task mafengwo, num 2
INFO 2012-08-16 15:17:02,244 models Will send task mafengwo, num 2
INFO 2012-08-16 15:17:02,245 clients Send jobs task num 2
INFO 2012-08-16 15:17:21,667 models Will handle task mafengwo, num 6
INFO 2012-08-16 15:17:21,668 models Will send task mafengwo, num 6
INFO 2012-08-16 15:17:21,669 clients Send jobs task num 6
ERROR 2012-08-16 15:36:48,334 base Internal Server Error: /
Traceback (most recent call last):
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 101, in get_response
    request.path_info)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/toureet/project/django-gearman/fish/urls.py", line 10, in <module>
    url(r'^tasks/', include('manager.urls')),
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 24, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/toureet/project/django-gearman/manager/urls.py", line 20, in <module>
    urlpatterns = url_pattern()
  File "/home/toureet/project/django-gearman/manager/urls.py", line 18, in url_pattern
    return patterns(prefix='', *ls)
TypeError: patterns() got multiple values for keyword argument 'prefix'
ERROR 2012-08-16 15:36:48,748 base Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/middleware/common.py", line 67, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 531, in is_valid_path
    resolve(path, urlconf)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 420, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/toureet/project/django-gearman/fish/urls.py", line 10, in <module>
    url(r'^tasks/', include('manager.urls')),
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 24, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/toureet/project/django-gearman/manager/urls.py", line 20, in <module>
    urlpatterns = url_pattern()
  File "/home/toureet/project/django-gearman/manager/urls.py", line 18, in url_pattern
    return patterns(prefix='', *ls)
TypeError: patterns() got multiple values for keyword argument 'prefix'
WARNING 2012-08-16 15:37:00,552 base Not Found: /
WARNING 2012-08-16 15:37:00,646 base Not Found: /favicon.ico
WARNING 2012-08-16 15:37:05,286 base Not Found: /tasks
WARNING 2012-08-16 15:37:05,379 base Not Found: /favicon.ico
WARNING 2012-08-16 15:37:09,750 base Not Found: /tasks/mafengwo
WARNING 2012-08-16 15:37:09,826 base Not Found: /favicon.ico
WARNING 2012-08-16 15:37:25,094 base Not Found: /tasks/mafengwo
WARNING 2012-08-16 15:37:25,182 base Not Found: /favicon.ico
WARNING 2012-08-16 15:37:57,414 base Not Found: /tasks/mafengwo
WARNING 2012-08-16 15:37:57,594 base Not Found: /favicon.ico
ERROR 2012-08-16 15:41:22,192 base Internal Server Error: /tasks/mafengwo
Traceback (most recent call last):
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/middleware/common.py", line 67, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 531, in is_valid_path
    resolve(path, urlconf)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 420, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/toureet/project/django-gearman/fish/urls.py", line 10, in <module>
    url(r'^tasks/', include('manager.urls')),
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 24, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/toureet/project/django-gearman/manager/urls.py", line 7, in <module>
    from views import task_dispatch
ImportError: cannot import name task_dispatch
ERROR 2012-08-16 15:41:22,474 base Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/middleware/common.py", line 67, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 531, in is_valid_path
    resolve(path, urlconf)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 420, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 298, in resolve
    for pattern in self.url_patterns:
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 328, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/toureet/project/django-gearman/fish/urls.py", line 10, in <module>
    url(r'^tasks/', include('manager.urls')),
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 24, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/toureet/project/django-gearman/manager/urls.py", line 7, in <module>
    from views import task_dispatch
ImportError: cannot import name task_dispatch
WARNING 2012-08-16 15:41:46,427 base Not Found: /tasks/mafengwo
WARNING 2012-08-16 15:41:46,630 base Not Found: /favicon.ico
WARNING 2012-08-16 15:41:58,920 base Not Found: /tasks/mafengwo
WARNING 2012-08-16 15:41:58,998 base Not Found: /favicon.ico
WARNING 2012-08-16 15:41:59,759 base Not Found: /tasks/mafengwo
WARNING 2012-08-16 15:41:59,827 base Not Found: /favicon.ico
WARNING 2012-08-16 15:42:04,686 base Not Found: /tasks/mafengwo
WARNING 2012-08-16 15:42:04,750 base Not Found: /favicon.ico
WARNING 2012-08-16 15:42:51,042 base Not Found: /tasks/mafengwo
WARNING 2012-08-16 15:42:51,177 base Not Found: /favicon.ico
WARNING 2012-08-16 15:42:55,055 base Not Found: /tasks/mafengwo/
WARNING 2012-08-16 15:42:55,150 base Not Found: /favicon.ico
WARNING 2012-08-16 15:43:22,916 base Not Found: /tasks/mafengwo/
ERROR 2012-08-16 15:43:24,166 base Internal Server Error: /tasks/mafengwo/
Traceback (most recent call last):
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
TypeError: task_dispatch() takes exactly 2 arguments (1 given)
WARNING 2012-08-16 15:43:24,328 base Not Found: /favicon.ico
WARNING 2012-08-16 15:45:03,186 base Not Found: /favicon.ico
WARNING 2012-08-16 15:48:34,510 base Not Found: /favicon.ico
WARNING 2012-08-16 15:48:38,217 base Not Found: /favicon.ico
WARNING 2012-08-16 15:48:54,135 base Not Found: /favicon.ico
WARNING 2012-08-16 15:49:33,393 base Not Found: /favicon.ico
WARNING 2012-08-16 15:49:36,298 base Not Found: /favicon.ico
WARNING 2012-08-16 15:49:40,477 base Not Found: /favicon.ico
WARNING 2012-08-16 15:50:44,097 base Not Found: /favicon.ico
WARNING 2012-08-16 15:50:57,622 base Not Found: /favicon.ico
WARNING 2012-08-16 16:00:42,065 base Not Found: /favicon.ico
INFO 2012-08-16 16:15:02,300 models Will handle task mafengwo, num 6
INFO 2012-08-16 16:15:02,301 models Will send task mafengwo, num 6
INFO 2012-08-16 16:15:02,302 clients Send jobs task num 6
WARNING 2012-08-16 16:15:26,911 base Not Found: /favicon.ico
INFO 2012-08-16 16:16:38,668 models Will handle task mafengwo, num 6
INFO 2012-08-16 16:16:38,669 models Will send task mafengwo, num 6
INFO 2012-08-16 16:16:38,670 clients Send jobs task num 6
INFO 2012-08-16 16:16:50,020 models Will handle task mafengwo, num 6
INFO 2012-08-16 16:16:50,021 models Will send task mafengwo, num 6
INFO 2012-08-16 16:16:50,022 clients Send jobs task num 6
INFO 2012-08-16 16:20:09,796 models Will handle task mafengwo, num 6
INFO 2012-08-16 16:20:09,797 models Will send task mafengwo, num 6
INFO 2012-08-16 16:20:09,797 clients Send jobs task num 6
INFO 2012-08-16 16:22:55,636 models Will handle task mafengwo, num 6
INFO 2012-08-16 16:22:55,637 models Will send task mafengwo, num 6
INFO 2012-08-16 16:22:55,637 clients Send jobs task num 6
INFO 2012-08-16 16:22:55,639 mafengwo On CallBack
INFO 2012-08-16 16:22:55,639 mafengwo On CallBack
INFO 2012-08-16 16:22:55,645 mafengwo On CallBack
INFO 2012-08-16 16:22:59,487 mafengwo On CallBack
INFO 2012-08-16 16:22:59,497 mafengwo On CallBack
INFO 2012-08-16 16:22:59,665 mafengwo On CallBack
INFO 2012-08-16 16:23:03,173 models Will handle task mafengwo, num 6
INFO 2012-08-16 16:23:03,173 models Will send task mafengwo, num 6
INFO 2012-08-16 16:23:03,174 clients Send jobs task num 6
INFO 2012-08-16 16:23:03,175 mafengwo On CallBack
INFO 2012-08-16 16:23:03,175 mafengwo On CallBack
INFO 2012-08-16 16:23:03,176 mafengwo On CallBack
INFO 2012-08-16 16:23:04,043 mafengwo On CallBack
INFO 2012-08-16 16:23:04,161 mafengwo On CallBack
INFO 2012-08-16 16:23:04,174 mafengwo On CallBack
INFO 2012-08-16 16:24:06,764 models Will handle task mafengwo, num 11
INFO 2012-08-16 16:24:06,765 models Will send task mafengwo, num 11
INFO 2012-08-16 16:24:06,765 clients Send jobs task num 11
INFO 2012-08-16 16:24:06,768 mafengwo On CallBack
INFO 2012-08-16 16:24:06,771 mafengwo On CallBack
INFO 2012-08-16 16:24:06,774 mafengwo On CallBack
INFO 2012-08-16 16:24:07,485 mafengwo On CallBack
INFO 2012-08-16 16:24:07,845 mafengwo On CallBack
INFO 2012-08-16 16:24:07,851 mafengwo On CallBack
INFO 2012-08-16 16:24:08,227 mafengwo On CallBack
INFO 2012-08-16 16:24:08,552 mafengwo On CallBack
INFO 2012-08-16 16:24:08,708 mafengwo On CallBack
INFO 2012-08-16 16:24:09,192 mafengwo On CallBack
INFO 2012-08-16 16:24:09,560 mafengwo On CallBack
INFO 2012-08-16 16:25:28,284 models Will handle task mafengwo, num 6
INFO 2012-08-16 16:25:28,285 models Will send task mafengwo, num 6
INFO 2012-08-16 16:25:28,285 clients Send jobs task num 6
INFO 2012-08-16 16:25:28,992 mafengwo Post It
INFO 2012-08-16 16:25:29,249 mafengwo Post It
INFO 2012-08-16 16:25:29,253 mafengwo Post It
INFO 2012-08-16 16:25:29,873 mafengwo Post It
INFO 2012-08-16 16:25:29,930 mafengwo Post It
INFO 2012-08-16 16:25:29,982 mafengwo Post It
INFO 2012-08-16 16:27:24,716 models Will handle task mafengwo, num 6
INFO 2012-08-16 16:27:24,717 models Will send task mafengwo, num 6
INFO 2012-08-16 16:27:24,718 clients Send jobs task num 6
INFO 2012-08-16 16:27:25,568 mafengwo Post It
INFO 2012-08-16 16:27:25,569 mafengwo post() argument after ** must be a mapping, not str
INFO 2012-08-16 16:27:25,609 mafengwo Post It
INFO 2012-08-16 16:27:25,609 mafengwo post() argument after ** must be a mapping, not str
INFO 2012-08-16 16:27:25,840 mafengwo Post It
INFO 2012-08-16 16:27:25,841 mafengwo post() argument after ** must be a mapping, not str
INFO 2012-08-16 16:27:26,288 mafengwo Post It
INFO 2012-08-16 16:27:26,289 mafengwo post() argument after ** must be a mapping, not str
INFO 2012-08-16 16:27:26,510 mafengwo Post It
INFO 2012-08-16 16:27:26,510 mafengwo post() argument after ** must be a mapping, not str
INFO 2012-08-16 16:27:26,771 mafengwo Post It
INFO 2012-08-16 16:27:26,771 mafengwo post() argument after ** must be a mapping, not str
INFO 2012-08-16 16:29:40,220 models Will handle task mafengwo, num 6
INFO 2012-08-16 16:29:40,221 models Will send task mafengwo, num 6
INFO 2012-08-16 16:29:40,222 clients Send jobs task num 6
INFO 2012-08-16 16:29:40,899 mafengwo 'function' object has no attribute 'post'
INFO 2012-08-16 16:29:41,217 mafengwo 'function' object has no attribute 'post'
INFO 2012-08-16 16:29:41,300 mafengwo 'function' object has no attribute 'post'
INFO 2012-08-16 16:29:41,740 mafengwo 'function' object has no attribute 'post'
INFO 2012-08-16 16:29:41,859 mafengwo 'function' object has no attribute 'post'
INFO 2012-08-16 16:29:41,987 mafengwo 'function' object has no attribute 'post'
INFO 2012-08-16 16:32:15,077 models Will handle task mafengwo, num 6
INFO 2012-08-16 16:32:15,078 models Will send task mafengwo, num 6
INFO 2012-08-16 16:32:15,078 clients Send jobs task num 6
INFO 2012-08-16 16:32:15,784 mafengwo Invalid scheme u'192.168.1.26'
INFO 2012-08-16 16:32:16,052 mafengwo Invalid scheme u'192.168.1.26'
INFO 2012-08-16 16:32:16,284 mafengwo Invalid scheme u'192.168.1.26'
INFO 2012-08-16 16:32:16,465 mafengwo Invalid scheme u'192.168.1.26'
INFO 2012-08-16 16:32:16,731 mafengwo Invalid scheme u'192.168.1.26'
INFO 2012-08-16 16:32:16,932 mafengwo Invalid scheme u'192.168.1.26'
INFO 2012-08-16 16:33:20,364 models Will handle task mafengwo, num 6
INFO 2012-08-16 16:33:20,365 models Will send task mafengwo, num 6
INFO 2012-08-16 16:33:20,367 clients Send jobs task num 6
INFO 2012-08-16 16:33:35,516 models Will handle task mafengwo, num 6
INFO 2012-08-16 16:33:35,517 models Will send task mafengwo, num 6
INFO 2012-08-16 16:33:35,517 clients Send jobs task num 6
INFO 2012-08-16 16:33:36,229 connectionpool Starting new HTTP connection (1): 192.168.1.26
ERROR 2012-08-16 16:33:36,239 base Internal Server Error: /tasks/manager.tasks.base
Traceback (most recent call last):
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/middleware/common.py", line 77, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.1.26:8000/tasks/manager.tasks.base/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
INFO 2012-08-16 16:33:36,303 mafengwo <Response [500]>
INFO 2012-08-16 16:33:36,489 connectionpool Starting new HTTP connection (1): 192.168.1.26
ERROR 2012-08-16 16:33:36,491 base Internal Server Error: /tasks/manager.tasks.base
Traceback (most recent call last):
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/middleware/common.py", line 77, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.1.26:8000/tasks/manager.tasks.base/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
INFO 2012-08-16 16:33:36,608 connectionpool Starting new HTTP connection (1): 192.168.1.26
ERROR 2012-08-16 16:33:36,616 base Internal Server Error: /tasks/manager.tasks.base
Traceback (most recent call last):
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/middleware/common.py", line 77, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.1.26:8000/tasks/manager.tasks.base/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
INFO 2012-08-16 16:33:36,633 mafengwo <Response [500]>
INFO 2012-08-16 16:33:36,695 mafengwo <Response [500]>
INFO 2012-08-16 16:33:37,138 connectionpool Starting new HTTP connection (1): 192.168.1.26
ERROR 2012-08-16 16:33:37,139 base Internal Server Error: /tasks/manager.tasks.base
Traceback (most recent call last):
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/middleware/common.py", line 77, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.1.26:8000/tasks/manager.tasks.base/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
INFO 2012-08-16 16:33:37,207 mafengwo <Response [500]>
INFO 2012-08-16 16:33:37,329 connectionpool Starting new HTTP connection (1): 192.168.1.26
ERROR 2012-08-16 16:33:37,330 base Internal Server Error: /tasks/manager.tasks.base
Traceback (most recent call last):
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/middleware/common.py", line 77, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.1.26:8000/tasks/manager.tasks.base/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
INFO 2012-08-16 16:33:37,393 mafengwo <Response [500]>
INFO 2012-08-16 16:33:37,492 connectionpool Starting new HTTP connection (1): 192.168.1.26
ERROR 2012-08-16 16:33:37,493 base Internal Server Error: /tasks/manager.tasks.base
Traceback (most recent call last):
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/middleware/common.py", line 77, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.1.26:8000/tasks/manager.tasks.base/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
INFO 2012-08-16 16:33:37,557 mafengwo <Response [500]>
INFO 2012-08-16 16:36:57,421 models Will handle task mafengwo, num 6
INFO 2012-08-16 16:36:57,421 models Will send task mafengwo, num 6
INFO 2012-08-16 16:36:57,422 clients Send jobs task num 6
INFO 2012-08-16 16:36:58,216 connectionpool Starting new HTTP connection (1): 192.168.1.26
WARNING 2012-08-16 16:36:58,225 base Not Found: /tasksMafengwoSpiderTask
INFO 2012-08-16 16:36:58,231 mafengwo <Response [404]>
INFO 2012-08-16 16:36:58,360 connectionpool Starting new HTTP connection (1): 192.168.1.26
WARNING 2012-08-16 16:36:58,362 base Not Found: /tasksMafengwoSpiderTask
INFO 2012-08-16 16:36:58,372 mafengwo <Response [404]>
INFO 2012-08-16 16:36:58,417 connectionpool Starting new HTTP connection (1): 192.168.1.26
WARNING 2012-08-16 16:36:58,418 base Not Found: /tasksMafengwoSpiderTask
INFO 2012-08-16 16:36:58,424 mafengwo <Response [404]>
INFO 2012-08-16 16:36:58,949 connectionpool Starting new HTTP connection (1): 192.168.1.26
WARNING 2012-08-16 16:36:58,951 base Not Found: /tasksMafengwoSpiderTask
INFO 2012-08-16 16:36:58,955 mafengwo <Response [404]>
INFO 2012-08-16 16:36:59,181 connectionpool Starting new HTTP connection (1): 192.168.1.26
WARNING 2012-08-16 16:36:59,182 base Not Found: /tasksMafengwoSpiderTask
INFO 2012-08-16 16:36:59,190 mafengwo <Response [404]>
INFO 2012-08-16 16:36:59,238 connectionpool Starting new HTTP connection (1): 192.168.1.26
WARNING 2012-08-16 16:36:59,239 base Not Found: /tasksMafengwoSpiderTask
INFO 2012-08-16 16:36:59,243 mafengwo <Response [404]>
INFO 2012-08-16 16:37:32,509 clients Send job task mafengwo, '{"SHUTDOWN": true}'
INFO 2012-08-16 16:37:32,511 models Dispatch a task name mafengwo, {u'SHUTDOWN': True}
INFO 2012-08-16 16:37:32,512 mafengwo u'start'
INFO 2012-08-16 16:37:32,513 mafengwo expected string or buffer
INFO 2012-08-16 16:37:32,642 clients Send job task mafengwo, '{"SHUTDOWN": true}'
INFO 2012-08-16 16:37:32,643 models Dispatch a task name mafengwo, {u'SHUTDOWN': True}
INFO 2012-08-16 16:37:32,643 mafengwo u'start'
INFO 2012-08-16 16:37:32,643 mafengwo expected string or buffer
INFO 2012-08-16 16:37:32,759 clients Send job task mafengwo, '{"SHUTDOWN": true}'
INFO 2012-08-16 16:37:32,759 models Dispatch a task name mafengwo, {u'SHUTDOWN': True}
INFO 2012-08-16 16:37:32,761 mafengwo u'start'
INFO 2012-08-16 16:37:32,761 mafengwo expected string or buffer
INFO 2012-08-16 16:38:06,668 models Will handle task mafengwo, num 6
INFO 2012-08-16 16:38:06,669 models Will send task mafengwo, num 6
INFO 2012-08-16 16:38:06,669 clients Send jobs task num 6
INFO 2012-08-16 16:38:07,356 connectionpool Starting new HTTP connection (1): 192.168.1.26
ERROR 2012-08-16 16:38:07,365 base Internal Server Error: /tasks/MafengwoSpiderTask
Traceback (most recent call last):
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/middleware/common.py", line 77, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.1.26:8000/tasks/MafengwoSpiderTask/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
INFO 2012-08-16 16:38:07,429 mafengwo <Response [500]>
INFO 2012-08-16 16:38:07,718 connectionpool Starting new HTTP connection (1): 192.168.1.26
ERROR 2012-08-16 16:38:07,719 base Internal Server Error: /tasks/MafengwoSpiderTask
Traceback (most recent call last):
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/middleware/common.py", line 77, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.1.26:8000/tasks/MafengwoSpiderTask/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
INFO 2012-08-16 16:38:07,757 connectionpool Starting new HTTP connection (1): 192.168.1.26
ERROR 2012-08-16 16:38:07,765 base Internal Server Error: /tasks/MafengwoSpiderTask
Traceback (most recent call last):
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/middleware/common.py", line 77, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.1.26:8000/tasks/MafengwoSpiderTask/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
INFO 2012-08-16 16:38:07,816 mafengwo <Response [500]>
INFO 2012-08-16 16:38:07,884 mafengwo <Response [500]>
INFO 2012-08-16 16:38:08,298 connectionpool Starting new HTTP connection (1): 192.168.1.26
ERROR 2012-08-16 16:38:08,299 base Internal Server Error: /tasks/MafengwoSpiderTask
Traceback (most recent call last):
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/middleware/common.py", line 77, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.1.26:8000/tasks/MafengwoSpiderTask/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
INFO 2012-08-16 16:38:08,386 mafengwo <Response [500]>
INFO 2012-08-16 16:38:08,498 connectionpool Starting new HTTP connection (1): 192.168.1.26
ERROR 2012-08-16 16:38:08,499 base Internal Server Error: /tasks/MafengwoSpiderTask
Traceback (most recent call last):
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/middleware/common.py", line 77, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.1.26:8000/tasks/MafengwoSpiderTask/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
INFO 2012-08-16 16:38:08,560 mafengwo <Response [500]>
INFO 2012-08-16 16:38:08,934 connectionpool Starting new HTTP connection (1): 192.168.1.26
ERROR 2012-08-16 16:38:08,935 base Internal Server Error: /tasks/MafengwoSpiderTask
Traceback (most recent call last):
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 89, in get_response
    response = middleware_method(request)
  File "/home/toureet/.virtualenvs/django-gearman/local/lib/python2.7/site-packages/django/middleware/common.py", line 77, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.1.26:8000/tasks/MafengwoSpiderTask/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
INFO 2012-08-16 16:38:08,996 mafengwo <Response [500]>
INFO 2012-08-16 16:39:41,628 models Will handle task mafengwo, num 6
INFO 2012-08-16 16:39:41,629 models Will send task mafengwo, num 6
INFO 2012-08-16 16:39:41,630 clients Send jobs task num 6
INFO 2012-08-16 16:39:42,348 connectionpool Starting new HTTP connection (1): 192.168.1.26
WARNING 2012-08-16 16:39:42,361 csrf Forbidden (CSRF cookie not set.): /tasks/MafengwoSpiderTask/
INFO 2012-08-16 16:39:42,364 mafengwo <Response [403]>
INFO 2012-08-16 16:39:42,495 connectionpool Starting new HTTP connection (1): 192.168.1.26
WARNING 2012-08-16 16:39:42,497 csrf Forbidden (CSRF cookie not set.): /tasks/MafengwoSpiderTask/
INFO 2012-08-16 16:39:42,499 mafengwo <Response [403]>
INFO 2012-08-16 16:39:42,634 connectionpool Starting new HTTP connection (1): 192.168.1.26
WARNING 2012-08-16 16:39:42,635 csrf Forbidden (CSRF cookie not set.): /tasks/MafengwoSpiderTask/
INFO 2012-08-16 16:39:42,638 mafengwo <Response [403]>
INFO 2012-08-16 16:39:43,124 connectionpool Starting new HTTP connection (1): 192.168.1.26
WARNING 2012-08-16 16:39:43,126 csrf Forbidden (CSRF cookie not set.): /tasks/MafengwoSpiderTask/
INFO 2012-08-16 16:39:43,128 mafengwo <Response [403]>
INFO 2012-08-16 16:39:43,261 connectionpool Starting new HTTP connection (1): 192.168.1.26
WARNING 2012-08-16 16:39:43,263 csrf Forbidden (CSRF cookie not set.): /tasks/MafengwoSpiderTask/
INFO 2012-08-16 16:39:43,265 mafengwo <Response [403]>
INFO 2012-08-16 16:39:43,609 connectionpool Starting new HTTP connection (1): 192.168.1.26
WARNING 2012-08-16 16:39:43,610 csrf Forbidden (CSRF cookie not set.): /tasks/MafengwoSpiderTask/
INFO 2012-08-16 16:39:43,612 mafengwo <Response [403]>
INFO 2012-08-16 16:41:27,668 models Will handle task mafengwo, num 6
INFO 2012-08-16 16:41:27,669 models Will send task mafengwo, num 6
INFO 2012-08-16 16:41:27,669 clients Send jobs task num 6
INFO 2012-08-16 16:41:28,432 connectionpool Starting new HTTP connection (1): 192.168.1.26
INFO 2012-08-16 16:41:28,444 mafengwo <Response [200]>
INFO 2012-08-16 16:41:28,720 connectionpool Starting new HTTP connection (1): 192.168.1.26
INFO 2012-08-16 16:41:28,723 mafengwo <Response [200]>
INFO 2012-08-16 16:41:28,738 connectionpool Starting new HTTP connection (1): 192.168.1.26
INFO 2012-08-16 16:41:28,741 mafengwo <Response [200]>
INFO 2012-08-16 16:41:29,259 connectionpool Starting new HTTP connection (1): 192.168.1.26
INFO 2012-08-16 16:41:29,262 mafengwo <Response [200]>
INFO 2012-08-16 16:41:29,390 connectionpool Starting new HTTP connection (1): 192.168.1.26
INFO 2012-08-16 16:41:29,393 mafengwo <Response [200]>
INFO 2012-08-16 16:41:29,509 connectionpool Starting new HTTP connection (1): 192.168.1.26
INFO 2012-08-16 16:41:29,511 mafengwo <Response [200]>
INFO 2012-08-16 16:44:23,069 models Will handle task mafengwo, num 6
INFO 2012-08-16 16:44:23,070 models Will send task mafengwo, num 6
INFO 2012-08-16 16:44:23,070 clients Send jobs task num 6
INFO 2012-08-16 16:44:23,875 mafengwo post() takes exactly 1 argument (2 given)
INFO 2012-08-16 16:44:23,929 mafengwo post() takes exactly 1 argument (2 given)
INFO 2012-08-16 16:44:24,280 mafengwo post() takes exactly 1 argument (2 given)
INFO 2012-08-16 16:44:24,597 mafengwo post() takes exactly 1 argument (2 given)
INFO 2012-08-16 16:44:24,888 mafengwo post() takes exactly 1 argument (2 given)
INFO 2012-08-16 16:44:24,929 mafengwo post() takes exactly 1 argument (2 given)
INFO 2012-08-16 16:45:39,516 models Will handle task mafengwo, num 11
INFO 2012-08-16 16:45:39,517 models Will send task mafengwo, num 11
INFO 2012-08-16 16:45:39,518 clients Send jobs task num 11
INFO 2012-08-16 16:45:40,302 connectionpool Starting new HTTP connection (1): 192.168.1.26
INFO 2012-08-16 16:45:40,313 mafengwo <Response [200]>
INFO 2012-08-16 16:45:40,538 connectionpool Starting new HTTP connection (1): 192.168.1.26
INFO 2012-08-16 16:45:40,541 mafengwo <Response [200]>
INFO 2012-08-16 16:45:40,805 connectionpool Starting new HTTP connection (1): 192.168.1.26
INFO 2012-08-16 16:45:40,808 mafengwo <Response [200]>
INFO 2012-08-16 16:45:41,067 connectionpool Starting new HTTP connection (1): 192.168.1.26
INFO 2012-08-16 16:45:41,069 mafengwo <Response [200]>
INFO 2012-08-16 16:45:41,268 connectionpool Starting new HTTP connection (1): 192.168.1.26
INFO 2012-08-16 16:45:41,276 mafengwo <Response [200]>
